### PR TITLE
Add test for pointer error in reflect.Into

### PR DESCRIPTION
**Pull request by abergmeier**
Main goal is to predict, which type should be used.

### CODE REVIEW

**Comment by abergmeier** [comment]
Not sure yet how to predict necessary type.

**Comment by abergmeier** [comment]
Is partial fix for https://github.com/hashicorp/terraform-plugin-framework/issues/283

**Comment by bflad** [comment]
Hi @abergmeier 👋  Thank you for raising this. It appears like the goal of this change is to return a "did you mean?" type recommendation from the internal/reflect logic errors. Is that the intention? If so, that seems like a nice enhancement.

Are you interested in continuing work on this? If so, it'd be great to work through this design more. Thanks again.

**Comment by bflad** [comment]
Closing due to https://github.com/hashicorp/terraform-plugin-framework/issues/283#issuecomment-1256296355 and lack of response here. Newer versions of the framework should provide some type hints in these cases, but if there is something specific that needs addressing, please raise a new issue. Thank you.

**Pull request closed without merging**
