### PR TITLE
attr: Added `IsNull()` and `IsUnknown()` methods to the `Value` interface type

### LINKED ISSUE #193: attr: Consider Adding IsNull() and IsUnknown() methods to Value
### Module version

```
v0.4.2
```

### Use-cases

When writing attribute plan modifiers, it can be necessary to check if the configuration or state `attr.Value` are null or unknown. It feels a little tedious to have to know the underlying value type for comparison and how to properly create the conditional.

### Attempted Solutions

```go
"function_name": {
			// Property: FunctionName
			// CloudFormation resource type schema:
			// {
			//   "description": "The name of the Lambda function, up to 64 characters in length. If you don't specify a name, AWS CloudFormation generates one.",
			//   "minLength": 1,
			//   "type": "string"
			// }
			Description: "The name of the Lambda function, up to 64 characters in length. If you don't specify a name, AWS CloudFormation generates one.",
			Type:        types.StringType,
			Optional:    true,
			Computed:    true,
			Validators: []tfsdk.AttributeValidator{
				validate.StringLenAtLeast(1),
			},
			PlanModifiers: []tfsdk.AttributePlanModifier{
				tfsdk.RequiresReplaceIf(func(ctx context.Context, state, config attr.Value, path *tftypes.AttributePath) (bool, diag.Diagnostics) {
					if config.Equal(state) || config.Equal(types.String{Null: true}) {
						return false, nil
					}

					return true, nil
				}, "require replacement if configuration value changes", "require replacement if configuration value changes"),
			},
		},
```

### Proposal

```go
type Value interface {
	// ... existing methods ...

	// IsNull returns true if the value is null.
	IsNull() bool

	// IsUnknown returns true if the value is unknown.
	IsUnknown() bool
}
```

For any `attr.Value` that potentially do not understand null/unknown, they can always return false for both methods. The implementation above then becomes:

```go
			PlanModifiers: []tfsdk.AttributePlanModifier{
				tfsdk.RequiresReplaceIf(func(ctx context.Context, state, config attr.Value, path *tftypes.AttributePath) (bool, diag.Diagnostics) {
					if config.Equal(state) || config.IsNull() {
						return false, nil
					}

					return true, nil
				}, "require replacement if configuration value changes", "require replacement if configuration value changes"),
			},
```

### PR DESCRIPTION
**Pull request by bflad**
Closes #193

### CODE REVIEW

**Review by kmoe — APPROVED** [review]
Needs review by @paddycarver but I'm on board with this as you [know](https://github.com/hashicorp/terraform-plugin-framework/blob/main/docs/design/plan-modification.md#requiresreplaceifset)!

**Comment by paddycarver** [comment]
Arguments for methods:

* Discoverability: because standalone functions aren't tied to the `attr.Value` type, they're not surfaced by the language server, godoc, etc. as things you can do.

**Comment by paddycarver** [comment]
We decided we wanted to wait on this momentarily until we can tackle #215, #172, and other refactoring issues, and refactor our package boundaries a little. Right now, it's a little hard to understand how large the discoverability tradeoff is going to be, just because we're guessing at what package architectures may be available in the future. I'm still hopeful we'll be able to have an `attr` package that wraps all this up neatly, but we can't today because we get import cycles. We'll return to this once we figure out what package boundaries we can draw after refactoring a bit.

**Comment by bflad** [comment]
I'm going to close this out for now given some other recent/upcoming changes. Can revisit this again in the future, if it makes sense.

**Pull request closed without merging**
