### PR TITLE
Add support for objects

### PR DESCRIPTION
**Pull request by paddycarver**
Adds the Object type and the ObjectType type. typetypetype.

Depends on #41.

### CODE REVIEW

**Comment by paddycarver** [comment]
Depends on #35.

**Review by kmoe — APPROVED** [review]
Looks good! Also depends on https://github.com/hashicorp/terraform-plugin-framework/pull/44.

**Comment by paddycarver** [comment]
Still happy with this @kmoe ?

**Comment by kmoe** [comment]
Yep! Hope you don't mind if I merge...

**Pull request merged**
