### PR TITLE
chore: Update Digital Team Files

### PR DESCRIPTION
**Pull request by hashibot-web**
# Description

Updates managed website-related files.

- `website/Makefile`
- `website/scripts/should-build.sh`
- `website/scripts/website-build.sh`
- `website/scripts/website-start.sh`

> **Note**
>
> This pull request was opened via the Digital team's automation. If you have questions, please tag @hashicorp/web-platform

### CODE REVIEW

**Comment by thiskevinwang** [comment]
👋 @hashicorp/terraform-devex could use a review + merge if this looks good!

**Comment by bflad** [comment]
@thiskevinwang Looks like the root directory `Makefile` was not updated in this repository 😉

**Comment by thiskevinwang** [comment]
@bflad Done (I committed but never pushed my local changes 🤦 )

**Review by bflad — APPROVED** [review]
Excellent! Thanks! 🚀

**Pull request merged**
