### PR TITLE
tfsdk: Automatic detection of attribute value normalization

### PR DESCRIPTION
**Pull request by apparentlymart**
This is a draft/prototype of what I was thinking about over in #70. For the moment this is just a hypothetical implementation to help with discussion over in that issue. I was mainly interested in seeing if I could achieve the effect I was describing in that issue (which I did) but I expect this probably isn't the best way to achieve that effect, if indeed that effect is even desirable in practice.

---

It's common for Terraform's very general definition of value equality to be stricter than a remote system's idea of equality. In that case, part of a provider's job is to classify each difference in value as either normalization or drift, or in other words to decide if a particular change is functionally significant to the remote system or if it's just a different way to write down what is effectively the same value.

The `attr.Value` interface already includes a method Equal, which allows defining value equality for a custom type in a more liberal way than Terraform's type system would define it.

Now we'll use that `Equal` method to automatically classify attribute value changes as normalization if the schema-defined type considers the old and new value as equal. In practice, that means that both `ReadResource` and `PlanResourceChange` will retain an attribute value from the prior state if the replacement new value is non-equal in Terraform terms but equal by
the provider's own definition.

Terraform Core's resource instance change lifecycle rules explicitly call for providers to return the prior state value if the new value from configuration is functionally-equivalent during `PlanResourceChange`. The documented rules don't discuss the expected behavior of `ReadResource` at all, but `ReadResource` also ultimately contributes to a diff (between the
prior state and the refreshed state) and it's important to use the same classification rules in both cases so that refreshing doesn't lead to situations where it takes multiple runs of `terraform apply` before the configuration and state can fully converge.

### CODE REVIEW

**Comment by apparentlymart** [comment]
Again really just out of curiosity I've added a second commit where I generalized the "case-insensitive-string" type that I had written only for the test case in the first commit, as one possible design for a convenient way to add additional normalization and validation rules to what is otherwise just a string.

That's not really the main point of the experiment here, but I wanted to explore a bit what it might actually look like for a provider codebase to use this in a real-world situation. One possible "specialized string" type could be a JSON string type that requires that its value be a valid JSON string and normalizes by regularizing the insignificant whitespace in some way.

**Comment by bflad** [comment]
@apparentlymart just to provide some additional context here -- I believe our generic solution in this space was going to allowing types in the framework's attribute type system to declare their own `PlanResourceChange` handlers (what we refer to colloquially as "plan modifiers"): https://github.com/hashicorp/terraform-plugin-framework/issues/161

There is, however, merit to the approach outlined here since the framework could automatically handle this class of equality use case and not require perfect type implementations. From a design perspective though, automatic behaviors in the framework are generally less preferred. I'm curious on @paddycarver's thoughts when back from vacation.

We also need to figure out what we want to do with relatively popular type use cases (such as JSON strings, timestamps, etc.), since the implementations likely will not be part of this project's codebase due to their maintenance burden and the generally slippery slope of which to include. I'm guessing we will wind up with _some_ centralized place though, maybe a framework/sdk counterpart to `terraform-plugin-go-contrib`, or maybe a separate `terraform-plugin-framework-types` repository.

**Comment by apparentlymart** [comment]
Thanks for that info, @bflad! That all makes sense to me, and I did this with the sense that it would be debateable whether the specific approach I took here would be "too magical".

One note I'll add is that I think it's important that providers handle this during `ReadResource` too -- not just in `PlanResourceChange` -- because otherwise we'll recreate the misbehavior of the old SDK where normalization can potentially take two runs of `terraform apply` to fully converge, as I was describing over in #70.

**Comment by bflad** [comment]
Hey @apparentlymart 👋  We are thinking of picking up this area of work in the coming weeks. Do you have interest in continuing on this and would you have some time to meet to discuss it?

**Pull request closed without merging**
